# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Cheke's Blog

# Short description (goes below the title; it will also be used in the RSS feed)
description: This is a sample Jekyll Blog.

# Your name, as you want it to appear underneath each post and in the footer
author: Sergio H. Cantu

# Your email if you want it to be linked on the contact page
author_email: scantu-at-mit.edu


# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap]

sass:
  sass_dir: assets/css
  style: :nested
