title:  "1Sergio Cantu's Blog"
tagline: "The story so far.."
description:
author:
  name: "Sergio Cantu"
  twitter: elchekchek

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'About me', file: 'facts.html'}
- {name: 'Research', file: 'resources.html'}
- {name: 'Grad Life', file: 'sample-posts.html'}
- {name: 'Projects', file: 'documentation.html'}
- {name: 'Outreach', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/elchekchek'}
- {icon: 'envelope', link: 'mailto:scanleo@me.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty
